In [1]:
import numpy as np

# 1. Carica i dati saltando la prima riga (intestazione)
dati = np.genfromtxt("vendite.csv", delimiter=",", skip_header=1, usecols=(1,2,3))

print("Array originale (6 mesi x 3 prodotti):")
print(dati)

# 2. Reshape a vettore piatto (18 valori)
flat = dati.reshape(-1)
print("Dati in formato piatto:", flat)

# 3. Reshape a (3,6) -> righe = prodotti, colonne = mesi
prodotti = dati.reshape(6, 3).T   # oppure: dati.T
print("Dati per prodotto (3 x 6):")
print(prodotti)

# 4a. Somma per mese
tot_mese = dati.sum(axis=1)
print("Totali mensili:", tot_mese)

# 4b. Somma per prodotto
tot_prod = prodotti.sum(axis=1)
print("Totali per prodotto:", tot_prod)


Array originale (6 mesi x 3 prodotti):
[[120.  80.  95.]
 [100.  75. 110.]
 [130.  90. 105.]
 [125.  85. 100.]
 [140. 100. 120.]
 [135.  95. 115.]]
Dati in formato piatto: [120.  80.  95. 100.  75. 110. 130.  90. 105. 125.  85. 100. 140. 100.
 120. 135.  95. 115.]
Dati per prodotto (3 x 6):
[[120. 100. 130. 125. 140. 135.]
 [ 80.  75.  90.  85. 100.  95.]
 [ 95. 110. 105. 100. 120. 115.]]
Totali mensili: [295. 285. 325. 310. 360. 345.]
Totali per prodotto: [750. 525. 645.]
